awesomeirko_gallery_user:
    resource: "@AwesomeirkoGalleryUserBundle/Resources/config/routing.yml"
    prefix:   /

awesomeirko_gallery:
    resource: "@AwesomeirkoGalleryBundle/Resources/config/routing.yml"
    prefix:   /

